name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: true
      options:
        - Android
        - iOS
        - macOS (Catalyst)
        - Windows
        - All
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
    validations:
      required: true
  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Exception / Stack Trace
      render: text
