name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform(s)
      multiple: true
      options:
        - Android
        - iOS
        - macOS (Catalyst)
        - Windows
        - All / Cross-platform
    validations:
      required: true
  - type: textarea
    id: api-proposal
    attributes:
      label: Proposed API
      render: csharp
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
