name: Release to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.2.3)'
        required: true
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  release-nuget:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install .NET MAUI Workload
        run: dotnet workload restore src\Plugin.Maui.Audio.sln

      - name: Restore dependencies
        run: dotnet restore src\Plugin.Maui.Audio.sln

      - name: Pack
        run: |
          $tagOrInput = "${{ inputs.version != '' && inputs.version || github.ref_name }}"
          $version = $tagOrInput.TrimStart("v")
          dotnet pack src\Plugin.Maui.Audio\Plugin.Maui.Audio.csproj -c Release -p:PackageVersion=$version -o artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: artifacts\*.nupkg

      - name: NuGet login (OIDC)
        uses: nuget/login@v1
        id: nuget-login
        with:
          user: jfversluis

      - name: Push to NuGet
        run: |
          dotnet nuget push artifacts\*.nupkg `
            --api-key "${{ steps.nuget-login.outputs.NUGET_API_KEY }}" `
            --source https://api.nuget.org/v3/index.json `
            --skip-duplicate
